Sunbird-Lern/userorg-service

service/app/controllers/audit/AuditLogController.java, service/app/controllers/coursemanagement/CourseBatchController.java, service/app/controllers/datapersistence/DbOperationController.java, service/app/controllers/geolocation/GeoLocationController.java, service/app/controllers/organisationmanagement/OrganisationController.java, service/app/controllers/usermanagement/UserController.java, service/app/util/Global.java
Changes for Login verification.
=> Issues #SB-4319 fix: changes for loging

service/app/mapper/RequestMapper.java, service/test/controllers/usermanagement/UserControllerTest.java
Issue #SB-2868 fix: fixes for Platform error 500  during when content-type header is missing
=> fixes for Platform error 500  thrown for client error

service/app/controllers/LearnerController.java, service/test/controllers/LearnerControllerTest.java
Bug fix SB- 4805 : View Course batch status
=> Bug fix SB- 4805 : View Course batch status

Jenkinsfile, service/conf/application.conf
Update registry environment configurations
=> Issue #SB-3198 feat: Update registry environment configurations

service/test/controllers/coursemanagement/CourseBatchControllerTest.java
Issue #SB-2733 fix: Course batch Update
=> Issue #SB-2733 fix: Course batch Update

service/app/controllers/organisationmanagement/OrganisationController.java, service/app/controllers/usermanagement/UserController.java, service/conf/routes, service/test/controllers/usermanagement/UserControllerTest.java
=> Issues #SB-5233 feat: removing un-used api

.gitmodules, Dockerfile, Jenkinsfile, metadata.sh, pom.xml, service/app/controllers/BaseController.java, service/app/controllers/skills/UserSkillController.java, service/app/controllers/skills/UserSkillEndorsementController.java, service/app/controllers/skills/validator/UserSkillEndorsementRequestValidator.java, service/app/controllers/skills/validator/UserSkillRequestValidator.java, service/app/controllers/systemsettings/SystemSettingsController.java, service/app/controllers/usermanagement/UserController.java, service/app/util/Global.java, service/app/util/RequestInterceptor.java, service/conf/log4j2.properties, service/conf/routes, service/test/controllers/BaseControllerTest.java, service/test/controllers/skills/UserSkillControllerTest.java, service/test/controllers/skills/UserSkillEndorsementControllerTest.java, service/test/controllers/skills/validator/UserSkillEndorsementRequestValidatorTest.java, service/test/controllers/skills/validator/UserSkillRequestValidatorTest.java, service/test/controllers/systemsettings/SystemSettingsControllerTest.java
merging release-1.10 with master.
=> Release 1.10

service/test/controllers/courseenrollment/CourseEnrollmentControllerTest.java
=> Issue #SB-7024 feat: Enroll API controller Test

service/app/controllers/courseenrollment/validator/CourseEnrollmentRequestValidator.java
Unenroll request validator fix
=> Issue #SB-7024 feat:Fix Unenroll request validator

service/test/controllers/LearnerControllerTest.java, service/test/controllers/audit/AuditLogControllerTest.java, service/test/controllers/badging/BadgeAssertionControllerTest.java, service/test/controllers/badging/BadgeIssuerControllerTest.java, service/test/controllers/badging/validator/BadgeClassValidatorTest.java, service/test/controllers/bulkapimanagement/BulkUploadControllerTest.java, service/test/controllers/clientmanagement/ClientControllerTest.java, service/test/controllers/config/ApplicationConfigControllerTest.java, service/test/controllers/courseenrollment/CourseEnrollmentControllerTest.java, service/test/controllers/coursemanagement/CourseBatchControllerTest.java, service/test/controllers/coursemanagement/CourseControllerTest.java, service/test/controllers/datapersistence/DbOperationControllerTest.java, service/test/controllers/geolocation/GeoLocationControllerTest.java, service/test/controllers/healthmanager/HealthControllerTest.java, service/test/controllers/location/LocationControllerTest.java, service/test/controllers/metrics/CourseMetricsControllerTest.java, service/test/controllers/metrics/OrganisationMetricsControllerTest.java, service/test/controllers/metrics/UserMetricsControllerTest.java, service/test/controllers/notesmanagement/NotesControllerTest.java, service/test/controllers/notificationservice/EmailServiceControllerTest.java, service/test/controllers/organisationmanagement/OrganisationControllerTest.java, service/test/controllers/pagemanagement/PageControllerTest.java, service/test/controllers/search/SearchControllerTest.java, service/test/controllers/skills/UserSkillControllerTest.java, service/test/controllers/skills/UserSkillEndorsementControllerTest.java, service/test/controllers/storage/FileStorageControllerTest.java, service/test/controllers/systemsettings/SystemSettingsControllerTest.java, service/test/controllers/tenantpreference/TenantPreferenceControllerTest.java, service/test/controllers/usermanagement/UserControllerTest.java
We will enable this one by one.
=> Commit changes for disabling failing tests in lms-service.

service/conf/routes
Update the mapping for the enroll and unenroll API gateway endpoint and removed the redundant API.
=> Issue SB-0000: Fix in mapping for the enroll and unenroll API

service/app/controllers/usermanagement/validator/UserRoleRequestValidator.java
=> Issue #SB-0000 feat: UserRoleRequestValidator change

service/test/controllers/usermanagement/UserControllerTest.java
=> userControllerTest

service/app/controllers/organisationmanagement/OrgTypeController.java, service/conf/routes, service/test/controllers/BaseControllerTest.java, service/test/controllers/organisationmanagement/OrgTypeControllerTest.java
=> OrgTypeControllerTest

service/test/controllers/usermanagement/UserStatusControllerTest.java
=> UserStatusControllerTest

service/test/controllers/usermanagement/UserRoleControllerTest.java
=> userRoleControlTest

service/test/controllers/coursemanagement/CourseBatchControllerTest.java
=> Course batch controller test

service/app/controllers/usermanagement/UserController.java, service/conf/routes
Changes for user profile read v2 api.
=> Issues #SB-8577 fix: changes for user profile v2 read

service/test/controllers/organisationmanagement/OrganisationControllerTest.java
=> org_controller_test2

service/app/controllers/pagemanagement/PageController.java
=> Issue #SB-9147 feat:Page Assemble

service/test/controllers/ApplicationTest.java, service/test/controllers/BaseControllerTest.java, service/test/controllers/LearnerControllerTest.java, service/test/controllers/audit/AuditLogControllerTest.java, service/test/controllers/coursemanagement/CourseBatchControllerTest.java, service/test/controllers/metrics/OrganisationMetricsControllerTest.java, service/test/controllers/organisationmanagement/OrgMemberControllerTest.java, service/test/controllers/organisationmanagement/OrgTypeControllerTest.java, service/test/controllers/organisationmanagement/OrganisationControllerTest.java, service/test/controllers/usermanagement/UserProfileControllerTest.java, service/test/controllers/usermanagement/UserRoleControllerTest.java, service/test/controllers/usermanagement/UserStatusControllerTest.java
=> Ignore test cases

service/app/controllers/BaseController.java, service/app/controllers/courseenrollment/CourseEnrollmentController.java, service/app/controllers/pagemanagement/PageController.java
=> Sb 9267 user course add data

service/pom.xml
akka-actor_2.11
also updated relevant jars to compatible versions.
=> solving the vulnerability reported by github for :

service/test/controllers/otp/OtpControllerTest.java
=> Issue #SC-0000 feat: otpcontroller test

service/app/controllers/usermanagement/UserDataEncryptionController.java, service/app/controllers/usermanagement/validator/UserDataEncryptionRequestValidator.java, service/conf/routes, service/test/controllers/usermanagement/UserDataEncryptionControllerTest.java
=> Encryption

README.md
Reverts project-sunbird/sunbird-lms-service#166
=> Revert "Revert "jenkins build trigger""

README.md
Reverts project-sunbird/sunbird-lms-service#167
=> Revert "Revert "Revert "jenkins build trigger"""

service/conf/routes
User Assign Role routes change
=> Another EndPoint of user Assign Role Public

service/app/controllers/usermanagement/UserRoleController.java, service/app/controllers/usermanagement/validator/UserRoleRequestValidator.java
=> Assign role bug fixes

service/app/controllers/badging/BadgeAssociationController.java, service/app/controllers/badging/validator/BadgeAssociationValidator.java, service/app/util/RequestInterceptor.java, service/conf/routes
Controller layer for badge association
=> Issue #SB-9852 feat: Badge Association

service/app/controllers/badging/BadgeAssociationController.java, service/app/controllers/badging/validator/BadgeAssociationValidator.java, service/app/util/RequestInterceptor.java, service/conf/routes
New API for Badge Association History/search
=> Badge association

service/test/controllers/usermanagement/UserTypeControllerTest.java
=> userTypeControllerTest

service/app/controllers/BaseController.java, service/app/controllers/healthmanager/HealthController.java, service/app/util/Global.java, service/conf/routes
=> Issue #SB-10876 feat: Added the check for service unavailability

service/app/controllers/BaseController.java, service/app/util/Global.java, service/app/util/RequestInterceptor.java
=> Health service

service/app/controllers/BaseController.java, service/app/util/Global.java
Capturing deviceid from the user request
=> Telemetry Events

service/app/controllers/BaseController.java, service/app/util/Global.java
Fixing APP-ID null pointer exception in request Header
=> x-api-id added

service/app/util/Filters.java, service/pom.xml, service/test/util/FilterTest.java
@bvinayakumar  please add   >>> sunbird_gzip_filter_enabled="True" <<< to env variable sheet for enabling gzip encoding, and for turning it off please add >>> sunbird_gzip_filter_enabled="False" <<<
By default it will be Turned OFF if not specified or for value other than "True"
=> configurable gzip filter added to learner searvice

service/app/controllers/BaseController.java, service/app/controllers/LearnerController.java, service/app/controllers/usermanagement/UserController.java, service/app/util/RequestInterceptor.java
Hot fix for checking federated userid
=> Issues #SB-12267 fix: changes for federated user id check

service/app/util/Global.java, service/app/util/RequestInterceptor.java
Telemetry :: {"eid":"AUDIT","ets":1564553680365,"ver":"3.0","mid":"1564553680365.61be21c3-d1a1-49cb-981b-c4cd0da81e47","actor":{"id":"46bb73f6-014d-4938-8969-50bd09ae7704","type":"User"},"context":{"channel":"0127766567206174720","pdata":{"id":"local.sunbird.learning.service","pid":"learning-service","ver":"2.0.0"},"env":"User","cdata":[{"id":"46bb73f6-014d-4938-8969-50bd09ae7704","type":"User"},{"id":"56456jk","type":"Request"}],"rollup":{"l1":"0127738024883077121"}},"object":{"id":"46bb73f6-014d-4938-8969-50bd09ae7704","type":"User"},"edata":{"state":"Update","props":["userId","password","id"]}}
=> Issue #SB-14101 feat: added teletery for reset password api

service/app/controllers/organisationmanagement/AssignKeysController.java, service/app/controllers/organisationmanagement/KeyManagementController.java, service/conf/routes
<b>Ticket Ref:</b> [SC-1190](https://project-sunbird.atlassian.net/browse/SC-1190)
1: Added routes file and controller action method IN AssignKeyController
2: API: `v1/org/assign/key` (PATCH)
3: Request Body:
`{
"request": {
"id":"0127311841811169280",
"signKeys": ["s3","s2"],
"encKeys": ["e5","e5"]
}
}`
=> IssueSC-1190 

service/app/controllers/certmanagement/CertificateController.java, service/conf/routes
created api end-point for merge user-cert: /private/user/v1/certs/merge
=> Sb 14223 merge user-cert api changes

service/conf/routes
Adding private endpoint for account merge.
=> Issue #SB-14373 fix:adding private endpoint for send notification

.travis.yml
fixes for travis build failure
=> issue #SB-14977 fix: changes for travis build fix

service/app/controllers/tenantmigration/TenantMigrationController.java, service/conf/routes
<b>Ticket Ref:</b> SC-1388
1: API is been added to handle the rejection of migration by User
2: API is :` /v1/user/migrate/reject/{userId}`
=> Issue#SC-1388 ADDED API TO HANDLE THE TENANT REJECTION

service/app/controllers/otp/validator/OtpRequestValidator.java
* Issue#SB-15220 added recoveryPhone and recoverEmail in allowed fields in otp generate
* Issue#SB-15220 added recoveryPhone and recoverEmail in allowed fields in otp generate
* SB-15509
=> SB-15220  (#323)

service/test/controllers/organisationmanagement/OrganisationControllerTest.java
Test case changes , instead of passing BigInt now passing Int value
=> issue #SB-15487 fix: test case change passing int instead of bigInt

service/test/controllers/organisationmanagement/OrganisationControllerTest.java
=> issue #SB-15791 fix: chnages for unit test

.gitmodules
=> issue #SC-1544 feat: changes for git submodule

service/app/controllers/usermanagement/UserController.java, service/conf/routes
1: /v1/user/existence/:key/:value  
TPS: 107/s
response : `{
"id": "api.user.existence.phone",
"ver": "v1",
"ts": "2019-12-21 00:06:47:543+0530",
"params": {
"resmsgid": null,
"msgid": null,
"err": null,
"status": "success",
"errmsg": null
},
"responseCode": "OK",
"result": {
"exists": true
}
}`
4: This APi will inform about the existence of the user only by email and phone
=> exist api added

.gitmodules, Jenkinsfile, service/app/controllers/BaseController.java, service/app/controllers/usermanagement/UserController.java, service/app/util/RequestInterceptor.java, service/conf/routes, service/test/controllers/usermanagement/UserControllerTest.java
merging release-2.6.5 to release-2.7.0
=> Merge 2.6.5 to 2.7.0

.gitmodules
=> Issue #SC-1619 feat:gitmodule file change

service/pom.xml
**Ticket Ref:** [SC-1632](https://project-sunbird.atlassian.net/browse/SC-1632?filter=10743)
1: Upgraded Jackson Dependency to 2.10.1 from 2.9.5
Refs:
- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core 
- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations
=> Issue#SC-1632 upgraded jackson version

service/app/controllers/healthmanager/HealthController.java, service/app/modules/SignalHandler.java, service/app/modules/StartModule.java
For gracefull shutdown of play server
https://www.playframework.com/documentation/2.8.x/Shutdown
=> Issue #SC-1722 feat: handling SIGTERM singnal for gracefull shutdown

service/app/controllers/BaseController.java
This change is intended to create a new tag. And we are making this log search improvement along.
=> Issue #SB-19112 Make the start operation easy to search

.gitmodules, service/app/controllers/otp/validator/OtpRequestValidator.java
Generate OTP API changes added for ward login
=> SH 55 Generate OTP API changes for managed user

service/app/controllers/otp/validator/OtpRequestValidator.java, service/app/controllers/tac/validator/UserTnCRequestValidator.java
- Validation for new field 'userId' in request payload
=> SH-136 Accept Terms and Conditions API changes

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/feed/FeedUtil.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/feed/FeedUtilTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/org/impl/OrganisationClientImpl.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/TenantMigrationActor.java, actors/sunbird-lms-mw/service/src/main/resources/application.conf, service/app/controllers/BaseController.java, service/app/controllers/notificationservice/EmailServiceController.java
These bugs fixed after 3.0.0 branch separated from 2.10.
Pre-Prod issues
=> Issue #SB-19446 merged bugs: SB-19300, SB-19334 from 2.10 to 3.0.0

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/EmailServiceActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/otp/OTPActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/otp/SendOTPActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/OTPUtil.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/otp/OTPActorTest.java, actors/sunbird-lms-mw/service/src/main/resources/application.conf
1.Shift background actor call before sending success response to caller in notification related Actor class
2. Added logs for analysis
3. Changed akka configuration for notification actor
=> Issue #SB-19484 feat: shift akka tell call and logs

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/AdminUtilHandler.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/models/adminutil/AdminUtilParams.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/models/adminutil/AdminUtilRequest.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/models/adminutil/AdminUtilRequestData.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/models/adminutil/AdminUtilRequestPayload.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/util/AdminUtilHandlerTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/user/UserClient.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/user/impl/UserClientImpl.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserService.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/impl/UserServiceImpl.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserManagementActorTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserManagementActorTestBase.java, service/app/controllers/usermanagement/UserController.java, service/conf/routes, service/test/controllers/usermanagement/UserControllerTest.java
Create  a new GET API with path as /v1/user/managed/:lua_uuid?withTokens=<boolean>
lua_uuid is mandatory
withTokens is an optional query param.
=> SH-379 Create a new API to fetch managedUsers of a uuid

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/user/UserClient.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/user/impl/UserClientImpl.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, service/app/controllers/usermanagement/UserController.java
Enhance the fetch managed users API to accept options sortBy and order
/managed/102fcbd2-8ec1-4870-b9e1-5dc01f2acc75?sortBy=createdDate&order=desc
=> SH-411 Enhance the fetch managed users API to accept options sortBy 

service/app/controllers/BaseController.java, service/app/util/RequestInterceptor.java
A search user API will not have the user id in the path or in the body. Catch UUID cast exception and handle null/emptiness of the same.
=> SH-461 Fix user search regression

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/BackGroundNotificationActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/SendNotificationActor.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/SendNotificationActorTest.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/notificationservice/SendNotificationActorTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-es-utils/src/main/java/org/sunbird/helper/ConnectionManager.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-notification/src/test/java/org/sunbird/notification/sms/BaseMessageTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-notification/src/test/java/org/sunbird/notification/sms/Message91Test.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/KeyCloakConnectionProvider.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/RequestValidator.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java, actors/sunbird-lms-mw/service/src/main/resources/application.conf, service/app/controllers/BaseController.java, service/app/controllers/notificationservice/EmailServiceController.java, service/app/modules/OnRequestHandler.java, service/app/util/RequestInterceptor.java, service/conf/routes, service/test/controllers/notificationservice/EmailServiceControllerTest.java
Added v2/notification end point for notifying user in async way via notification service
=> Issue #TG-125 feat:add new v2 notification endpoint

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserProfileReadActorTest.java, service/app/controllers/usermanagement/UserController.java, service/app/util/CaptchaHelper.java, service/conf/routes, service/test/controllers/usermanagement/UserControllerTest.java, service/test/util/CaptchaHelperTest.java
It checks wheather user exists or not and provide the response as:
`{
"id": "api.user.exists.email",
"ver": "v2",
"ts": "2020-07-08 23:18:19:480+0530",
"params": {
"resmsgid": null,
"msgid": "4561ca4f-809a-46b4-a766-58db12546b16",
"err": null,
"status": "success",
"errmsg": null
},
"responseCode": "OK",
"result": {
"managedBy": "",
"name": "localuser116localuser113",
"exists": true,
"id": "41d5afa9-da67-41dc-a1a1-ed361db5d041"
}
}`
=> Issue #SH-587 user-exists api v2

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/services/sso/impl/KeyCloakServiceImpl.java
=> Issue #SB-19800 feat: read kc public key from env

Dockerfile, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraDACImpl.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java, service/conf/logback.xml
Write all cassandra query to kafka for analyzing the performance of query.
=> Issue #TG-377 feat:add cassandra query log to kafka

service/conf/routes
For now, this API is pointing to healthContoller (as I am onboarding this API now). @sknirmalkar89  is working on this API and will revert changes
=> SB-19960: added new end point v1/user/declarations

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties, service/app/controllers/usermanagement/UserController.java, service/app/util/CaptchaHelper.java, service/test/controllers/usermanagement/UserControllerTest.java, service/test/util/CaptchaHelperTest.java
For mobile app get separate captcha secret key for validation.
=> SH-835 For mobile app get mobile secret key for captcha validation

actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
Fixes:
1. Updating createdBy and updatedBy with callerId rather expecting them in the request.
2. Update status as PENDING by default when self declared add operation is performed.
3. Read api is changed to give declared info in sync with updated Api structure.
=> SC-1882 updating createdBy or updated through callerId

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/pom.xml, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-es-utils/pom.xml, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-core/pom.xml, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/pom.xml, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/pom.xml, service/conf/application.conf, service/pom.xml
Using Netty server instead of Akka Http server for better TCP handshake.
Akka http server used to send RST instead of FIN/ACK.
=> Issue #TG-217 feat:using netty server for better TCP connection handling

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/SendNotificationActor.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/notificationservice/SendNotificationActorTest.java
in params request for v2 notification added placeholder related to course completion certificate.
=> Sb 20039 Roll forward to 3.2

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/tenantpreference/TenantPreferenceManagementActor.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/tenantpreference/TenantPreferenceManagementActorTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java, service/app/controllers/tenantpreference/TenantPreferenceController.java, service/app/controllers/tenantpreference/TenantPreferenceValidator.java, service/app/util/RequestInterceptor.java, service/conf/routes, service/test/controllers/tenantpreference/TenantPreferenceControllerTest.java
End Point : **/v2/org/preferences/update**
**Request** : `{
"request":{
"orgId":"",
"key": "",
"data": {
}
}
}`
**Response**: `{
"id": "api.org.preferences.update",
"ver": "v1",
"ts": "2020-08-06 23:24:56:485+0530",
"params": {
"resmsgid": null,
"msgid": "a670b165-d8eb-4b02-b98a-ee47d7e34f5f",
"err": null,
"status": "success",
"errmsg": null
},
"responseCode": "OK",
"result": {
"response": "SUCCESS"
}
}`
End point: **/v2/org/preferences/read**
**Request**: `{
"request":{
"orgId":"",
"key": ""
}
}`
**Response**: `{
"id": "api.org.preferences.read",
"ver": "v1",
"ts": "2020-08-06 23:25:12:753+0530",
"params": {
"resmsgid": null,
"msgid": "a2a5d2fb-7ce1-4280-9bf1-d12d289a7822",
"err": null,
"status": "success",
"errmsg": null
},
"responseCode": "OK",
"result": {
"response": {
"updatedBy": …
=> SC-1886: Enhance tenant preferences read and update api

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java
Username change from regional language to english. Implemented in 
- /v1/user/create
- /v2/user/create
- /v3/user/create
- /v4/user/create
=> SB-19898 Diksha ID (the readable ID on the Diksha profile) should not be in regional language

actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
when unknown channel is passed there is no mapping found which causing null pointer exception.. fix will throw invalid parameter error if invalid channel is passed
=> SC-1907 Fix exception code when invalid channel is passed

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserExternalIdentityAdapter.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserManagementActorTestBase.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserSelfDeclarationManagementActorTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserExternalIdentityAdapterTest.java, service/test/controllers/usermanagement/UserControllerTest.java
Created new constant for teacher persona instead of using a constant that refers to user type
=> SB-20237 Change persona constant in self declaration Bulk Upload

actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
Support read orgId from provider  provided in any case
=> SC-1990 case insensitive support for channel

.circleci/config.yml, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/request/UserRequestValidatorTest.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserUtilTest.java
FIx:
1. Masked value for email and phone will have the data copied from database
2. Map in cassandra does not support null value, hence a validation check if info fields contains null value then throw client error
3. If Status is not present in the declartion object Default it to PENDING
=> SH-1054 Encrypt and store masked email/phone first time

actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java
Remove unused method and refactored method impl for v1, v2 userExists.
=> SB-19848 Refactor user exists API

Jenkinsfile
Changed Jenkins file command from mvn test to mvn clean install to run all the controller test cases
=> Sb 20562 fix for controller test case

service/conf/logback.xml
fixed logback file for writting telemetry in kafka
=> Sc 2016 fixed logback file for writting telemetry in kafka

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/bean/SelfDeclaredUser.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkMigrationActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/model/SelfDeclaredErrorTypeEnum.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActorTest.java, actors/sunbird-lms-mw/actors/common/src/test/resources/BulkSelfDeclaredUserUploadEmpty.csv, actors/sunbird-lms-mw/actors/common/src/test/resources/BulkSelfDeclaredUserUploadImproperSample.csv, actors/sunbird-lms-mw/actors/common/src/test/resources/BulkSelfDeclaredUserUploadSample.csv, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties, service/conf/logback.xml
Removed Diksha Sub Org ID(optional) column from the csv.
When Sub Org Ext ID(schooludiseid) is provided it is check against the admin root-org, i.e sub-org should be part of the state-admin org.
=> SC-2017 Declaration upload, allow only valid sub-org root-org

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/otp/OTPActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/OTPUtil.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/util/OTPUtilTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserLookupTest.java
If generated OTP length is less than 4, then regenerate OTP(max retry 3 times) ;
=> Sb 20561: Ensure OTP length is at least 4 characters

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/EmailServiceActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/mail/SendgridConnection.java
Resetting OTP connection every minute
=> Issue #TG-000 feat: otp fix

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/ActorOperations.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/BaseRequestValidator.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserFeedActor.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserFeedActorTest.java, service/app/controllers/feed/FeedController.java, service/app/controllers/feed/validator/FeedRequestValidator.java, service/conf/routes, service/test/controllers/BaseApplicationTest.java, service/test/controllers/bulkapimanagement/BulkUploadControllerTest.java, service/test/controllers/config/ApplicationConfigControllerTest.java, service/test/controllers/feed/FeedControllerTest.java, service/test/controllers/feed/validator/FeedRequestValidatorTest.java, service/test/controllers/geolocation/GeoLocationControllerTest.java, service/test/controllers/notificationservice/EmailServiceControllerTest.java, service/test/controllers/search/SearchControllerTest.java, service/test/controllers/storage/FileStorageControllerTest.java
Save user-feed in learner.
While saving user-feed not checking whether user crossed 30 feed and not deleted old one's.
=> SB-20928 create user-feed api

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/validator/user/UserBulkMigrationRequestValidator.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActorTest.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/validator/user/UserBulkMigrationRequestValidatorTest.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/TenantMigrationActor.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/actors/TenantMigrationActorTest.java
=> SH-1349 Admin is not able to upload self declared CSV file with particular error types

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
Added logs to trace the request which updates user location.
=> Issue #SB-21114

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, service/app/controllers/BaseController.java
Added logs to check the location missing issue
=> Issue #SB-21114 : Added logs to check the location missing issue

actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/validator/user/UserBulkMigrationRequestValidatorTest.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandra/CassandraOperation.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-cassandra-utils/src/main/java/org/sunbird/cassandraimpl/CassandraOperationImpl.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/RequestContext.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/TenantMigrationActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserService.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/impl/UserServiceImpl.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserLookUp.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserManagementActorTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserServiceGenerateUsernameTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/SetUserDefaultValueTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserLookupTest.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserUtilTest.java, service/app/controllers/BaseController.java
Code changes from release-3.3.0 hot-fix changes to release-3.4.0
=> Release 3.4.0 latestchanges

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/notificationservice/EmailServiceActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/mail/SendEmail.java
Reverts project-sunbird/sunbird-lms-service#617
=> Revert "Issue #SB-21978 feat:Added log for checking notification issue"

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-core/src/main/java/org/sunbird/actor/router/RequestRouter.java, actors/sunbird-lms-mw/service/src/main/resources/application.conf, service/app/controllers/BaseController.java, service/app/modules/OnRequestHandler.java, service/conf/application.conf, service/test/controllers/BaseApplicationTest.java, service/test/controllers/TestUtil.java, service/test/controllers/certmanagement/CertificateControllerTest.java, service/test/controllers/organisationmanagement/OrgMemberControllerTest.java, service/test/controllers/organisationmanagement/OrgTypeControllerTest.java, service/test/controllers/organisationmanagement/OrganisationControllerTest.java, service/test/controllers/otp/OtpControllerTest.java, service/test/controllers/tac/TnCControllerTest.java, service/test/controllers/usermanagement/UserControllerTest.java, service/test/controllers/usermanagement/UserRoleControllerTest.java, service/test/controllers/usermanagement/UserStatusControllerTest.java, service/test/controllers/usermanagement/UserTypeControllerTest.java
Returning traceId and error code in response.
Disable log at start of akka in play framework.
Disabled few logs which were not useful for debugging by changing log level
=> Issue # SB-21785

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/health/HealthActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/request/UserRequestValidator.java, service/app/controllers/healthmanager/HealthController.java
1. Removed search_service_api_base_url call from learner.
2. Fixed 500 error of user update API.
=> Issue #SB-000 feat:Fixed user update 500 error

actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserProfileReadService.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/service/UserProfileReadServiceTest.java
update api with same school with multiple times not worked, this is fixed.(which means only 2 active orgs will be associated to the user)
read api corrected with proper school details
=> SB-22676  adding exact school details in read-api and while updating the same school details now only 2 orgs will be present

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/validator/user/UserRequestValidator.java
Set default if persona is not passed
=> SB-22787 Fix:Allow roles to be submitted 

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/search/SearchHandlerActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserProfileReadService.java
Reverts project-sunbird/sunbird-lms-service#722 to fix backward compatibility
=> Revert "SC-2232 user search and read api changes"

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/search/SearchHandlerActor.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserProfileReadService.java
Reverts project-sunbird/sunbird-lms-service#733
=> SC-2232 user search and read api changes

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/actor/background/ChannelRegistrationActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/common/ShadowUserProcessor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/BackgroundJobManager.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/OrganisationManagementActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/search/SearchHandlerActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/syncjobmanager/EsSyncBackgroundActor.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/DataCacheHandler.java, actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/Util.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/OrgManagementActorTest.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/SearchHandlerActorTest.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/util/UtilTest.java, actors/sunbird-lms-mw/actors/common/src/test/resources/BulkOrgUploadEmptyFile.csv, actors/sunbird-lms-mw/actors/common/src/test/resources/BulkOrgUploadSample.csv, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/models/organisation/Organisation.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java, actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/cassandratablecolumn.properties, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/TenantMigrationActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserOrgManagementActor.java, actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/actors/UserOrgManagementActorTest.java, actors/sunbird-lms-mw/service/src/main/resources/application.conf, service/app/controllers/sync/SyncController.java, service/app/controllers/tenantmigration/TenantMigrationController.java, service/app/modules/OnRequestHandler.java, service/test/controllers/BaseApplicationTest.java
Changes:
1. Removed code related to HashTagId
2. Fixed org/user search with fields for default values
3. removed unused code
4. change related to isSchool search in org search api
5. fixed test cases
6. ES Sync code change
=> Sc 2221 hashtagid change

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/FormApiUtilHandler.java, actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/util/FormApiUtilHandlerTest.java
This logs are needed to have a information about states missing form-config details.
=> SB-24240 added for better logging

actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
Purge unnecessary attributes from user and organisation tables
=> SC-2214 Purge unnecessary attributes from user and organisation tables

service/conf/routes, service/test/controllers/scheduler/SchedulerControllerTest.java, service/test/controllers/usermanagement/UserTypeControllerTest.java
API list
/v1/user/update/logintime
/v1/user/type/list
/v2/bulk/user/upload
/private/user/v1/scheduler
=> SC-2266 Remove 4 unused APIs from learners

actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/search/SearchHandlerActor.java, actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserOrgManagementActor.java
fix for search v1/v2
in create user v1/v2/v3 cust-organisation is not added
=> SB-25485 fix for search for version v1/v2 roles not popuped when unassociated org added

service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java, service/src/test/java/org/sunbird/actor/user/UserUpdateActorTest.java
https://project-sunbird.atlassian.net/browse/SB-27483
=> SB-27483 : Removed duplicates from userProfileTypes

service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java
https://project-sunbird.atlassian.net/browse/SB-27483
=> Issue #SB-27483 feat: Removed duplicates from userProfileTypes

service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java
https://project-sunbird.atlassian.net/browse/SB-27483
=> SB-27483 : Remove userProfiles update from user v2/v1 update API

service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java, service/src/main/java/org/sunbird/actor/user/validator/UserRequestValidator.java
SB-27485 New v3 upadte API is allowing to give subtype for teacher, student and parent
=> SB-27485 New v3 upadte API is allowing to give subtype for teacher, student and parent

service/src/main/java/org/sunbird/actor/bulkupload/LocationBulkUploadBackGroundJobActor.java, service/src/main/java/org/sunbird/actor/bulkupload/OrgBulkUploadBackgroundJobActor.java, service/src/test/java/org/sunbird/actor/user/UserManagementActorTestBase.java, service/src/test/java/org/sunbird/actor/user/UserProfileReadActorTest.java, service/src/test/java/org/sunbird/actor/user/UserUpdateActorTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SC-2324" title="SC-2324" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SC-2324</a>  Refactoring Location bulk upload Module
</td></table>
<br />
=> SC-2324 Refactoring Location bulk upload Module

core/platform-common/src/main/java/org/sunbird/logging/LoggerUtil.java, core/platform-common/src/main/java/org/sunbird/telemetry/util/TelemetryGenerator.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-21780" title="SB-21780" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-21780</a>  Change all logs to follow the standard log format  - User Org-learner
</td></table>
<br />
* …
=> SB-21780 corrected info log structure with request-context

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, service/src/main/java/org/sunbird/service/user/UserTncService.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27815" title="SB-27815" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-27815</a>  Terms & policies page throwing up technical error
</td></table>
<br />
=> SB-27815 Terms & policies page throwing up technical error

pom.xml, service/src/test/java/org/sunbird/actor/notes/NotesManagementActorTest.java, service/src/test/java/org/sunbird/actor/search/SearchHandlerActorTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27815" title="SB-27815" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-27815</a>  Terms & policies page throwing up technical error
</td></table>
<br />
=> SB-27815 Testcase fixes

service/src/main/java/org/sunbird/service/user/UserTncService.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27815" title="SB-27815" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-27815</a>  Terms & policies page throwing up technical error
</td></table>
<br />
=> Issue # SB-27815 feat: fix tnc issue

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, pom.xml, service/src/main/java/org/sunbird/service/user/UserTncService.java, service/src/test/java/org/sunbird/actor/notes/NotesManagementActorTest.java, service/src/test/java/org/sunbird/actor/search/SearchHandlerActorTest.java
=> Merge release-4.4.0 to master

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, pom.xml, service/src/main/java/org/sunbird/actor/feed/UserFeedActor.java, service/src/main/java/org/sunbird/service/feed/IFeedService.java, service/src/main/java/org/sunbird/service/feed/impl/FeedServiceImpl.java, service/src/test/java/org/sunbird/actor/user/UserFeedActorTest.java, service/src/test/java/org/sunbird/service/feed/impl/FeedServiceImplTest.java
Mobile : User is not getting the notification for certificate download.
=> SB-27915:Mobile : User is not getting the notification for certificate download.

Dockerfile
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28017" title="SB-28017" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype" />SB-28017</a>  Fix Log 4j vulnerability in learner service
</td></table>
<br />
=> SB-28017 Fix Log 4j vulnerability in learner service

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/resources/externalresource.properties, service/src/main/java/org/sunbird/actor/feed/UserFeedActor.java, service/src/main/java/org/sunbird/client/NotificationServiceClient.java, service/src/main/java/org/sunbird/service/feed/FeedFactory.java, service/src/main/java/org/sunbird/service/feed/impl/FeedServiceImpl.java, service/src/test/java/org/sunbird/service/feed/impl/FeedServiceImplTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28035" title="SB-28035" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype" />SB-28035</a>  Refactor learner feed api
</td></table>
<br />
Refactor User feed service
=> SB-28035: Refactor feed service

service/src/main/java/org/sunbird/actor/role/FetchUserRoleActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27557" title="SB-27557" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-27557</a>  Reviewer email notification - Creator filed is getting set as undefined
</td></table>
<br />
* …
=> Sb 27557 v2

controller/app/controllers/usermanagement/validator/UserRoleRequestValidator.java, controller/test/controllers/usermanagement/UserRoleControllerTest.java, controller/test/controllers/usermanagement/validator/UserRoleRequestValidatorTest.java, core/platform-common/src/main/resources/externalresource.properties, pom.xml, service/src/main/java/org/sunbird/actor/user/UserTnCActor.java, service/src/main/java/org/sunbird/service/user/UserProfileReadService.java, service/src/main/java/org/sunbird/service/user/UserRoleService.java, service/src/main/java/org/sunbird/service/user/UserTncService.java, service/src/main/java/org/sunbird/service/user/impl/UserRoleServiceImpl.java, service/src/main/java/org/sunbird/service/user/impl/UserServiceImpl.java, service/src/main/java/org/sunbird/util/Util.java, service/src/main/java/org/sunbird/util/user/UserTncUtil.java, service/src/test/java/org/sunbird/actor/user/UserTnCActorTest.java, service/src/test/java/org/sunbird/service/user/UserTncServiceTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27873" title="SB-27873" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-27873</a>  Assign role API - Add scope validations
</td></table>
<br />
=> Sb 27873 v2

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/resources/externalresource.properties, service/src/main/java/org/sunbird/actor/organisation/OrganisationManagementActor.java, service/src/main/java/org/sunbird/service/organisation/OrgService.java, service/src/main/java/org/sunbird/service/organisation/impl/OrgServiceImpl.java, service/src/test/java/org/sunbird/service/organisation/OrgServiceImplTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27867" title="SB-27867" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-27867</a>  Dependency on channel APIs need to be made configurable to enable and disable as per the adopter need
</td></table>
<br />
**Test …
=> Issue #SB-27867 feat: Making channel registration configurable

service/src/main/java/org/sunbird/actor/user/ManagedUserActor.java, service/src/main/java/org/sunbird/actor/user/SSUUserCreateActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28183" title="SB-28183" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28183</a>  SSU User org association issue
</td></table>
<br />
=> Issue #SB-28183 feat:Fixed ssu user org association

service/src/main/java/org/sunbird/actor/user/ManagedUserActor.java, service/src/main/java/org/sunbird/actor/user/SSUUserCreateActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28183" title="SB-28183" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-28183</a>  SSU User org association issue
</td></table>
<br />
=> Issue #SB-28183 feat:SSU user org association fix

core/es-utils/pom.xml, core/platform-common/pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28017" title="SB-28017" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28017</a>  Fix Log 4j vulnerability in learner service
</td></table>
<br />
=> Issue #SB-28017 feat: upgraded es rest client

pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28331" title="SB-28331" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28331</a>  Org search for school association should check org is active or inactive
</td></table>
<br />
* Software …
=> Issue #SB-28331 feat:merge release-4.5 to 4.6

core/platform-common/src/main/resources/externalresource.properties, service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28331" title="SB-28331" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28331</a>  Org search for school association should check org is active or inactive
</td></table>
<br />
* Software …
=> Issue#SB-28331 feat:search only active org while user org association

core/platform-common/src/main/java/org/sunbird/http/HttpClientUtil.java, service/src/main/java/org/sunbird/client/NotificationServiceClient.java, service/src/test/java/org/sunbird/actor/user/SSUUserCreateActorTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28414" title="SB-28414" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28414</a>  Certifcation notification job failing due to UTF-8 encoding data while calling notification service
</td></table>
<br />
Fix utf-8 encoding failed due to request containing non utf-8 characters
=> SB-28414:Certification notification job failing due utf-8 encoding issue

core/platform-common/src/main/java/org/sunbird/telemetry/util/TelemetryGenerator.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28430" title="SB-28430" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28430</a>  New user's entry is missing in the all 3 exhaust reports
</td></table>
<br />
* Hardware …
=> SB-28430 removed requestid from edata

pom.xml, service/src/main/java/org/sunbird/actor/user/SSOUserCreateActor.java, service/src/main/java/org/sunbird/actor/user/UserBaseActor.java, service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java, service/src/main/java/org/sunbird/service/user/UserProfileReadService.java, service/src/test/java/org/sunbird/actor/user/ManagedUserActorTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28164" title="SB-28164" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28164</a>  School as location concept need to be completely removed
</td></table>
<br />
* Hardware …
=> Issue #SB-28164 feat:Remove school as location

core/platform-common/src/main/java/org/sunbird/telemetry/util/TelemetryGenerator.java, service/src/main/java/org/sunbird/client/NotificationServiceClient.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28384" title="SB-28384" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28384</a>  New and updated user details are not shown in userinfo and progress exhaust reports 
</td></table>
<br />
* …
=> Issue #SB-28384 feat: Merge release-4.5 to release-4.6

core/platform-common/src/main/java/org/sunbird/http/HttpClientUtil.java, core/platform-common/src/main/java/org/sunbird/telemetry/util/TelemetryGenerator.java, service/src/main/java/org/sunbird/client/NotificationServiceClient.java, service/src/test/java/org/sunbird/actor/user/SSUUserCreateActorTest.java
=> Merging 4.6 to master

core/platform-common/src/main/java/org/sunbird/http/HttpClientUtil.java, core/platform-common/src/main/java/org/sunbird/telemetry/util/TelemetryGenerator.java, service/src/main/java/org/sunbird/client/NotificationServiceClient.java
=> Merging master to 4.7

service/src/main/java/org/sunbird/actor/role/UserRoleActor.java, service/src/main/java/org/sunbird/service/role/RoleService.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28560" title="SB-28560" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-28560</a>  UserRoleAssign API - throws error when user has roles which are deprecated
</td></table>
<br />
* Software …
=> issue #SB-28560 feat:handling depricated role in v2 assign role api

service/src/main/java/org/sunbird/actor/role/UserRoleActor.java, service/src/main/java/org/sunbird/actor/user/TenantMigrationActor.java, service/src/main/java/org/sunbird/actor/userconsent/UserConsentActor.java, service/src/main/java/org/sunbird/service/role/RoleService.java, service/src/test/java/org/sunbird/actor/user/SSUUserCreateActorTest.java
=> SB-28560 Merging 4.6 fixes

controller/app/controllers/BaseController.java, controller/app/util/PrintEntryExitLog.java, controller/app/util/RequestInterceptor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22288" title="SB-22288" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-22288</a>  Return specific "error code" in the response - User, Org - learner
</td></table>
<br />
* …
=> Issue #SB-22288 feat: Handle ClientErrorResponse scenario

controller/app/modules/OnRequestHandler.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22288" title="SB-22288" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-22288</a>  Return specific "error code" in the response - User, Org - learner
</td></table>
<br />
* …
=> Issue #SB-22288 feat: Fixing env in requestContext

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, service/src/main/java/org/sunbird/actor/user/TenantMigrationActor.java, service/src/main/java/org/sunbird/actor/userconsent/UserConsentActor.java
=> Merge4.6fixes

service/src/main/java/org/sunbird/actor/user/ManagedUserActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28937" title="SB-28937" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28937</a>  User not able add MUA users with some LIUA & getting error message
</td></table>
<br /> …
=> Issue #SB-28937 feat:Fixed MUA user issue related to orgExtId

controller/app/controllers/BaseController.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-22288" title="SB-22288" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-22288</a>  Return specific "error code" in the response - User, Org - learner
</td></table>
<br />
* …
=> Issue #SB-22288 feat: Fixed Error code issue for search API

core/es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java, core/es-utils/src/main/java/org/sunbird/common/ElasticSearchRestHighImpl.java, core/es-utils/src/main/java/org/sunbird/dto/SearchDTO.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29813" title="SB-29813" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29813</a>  OrgSearch to allow partial search and fuzzy Search
</td></table>
<br />
* Hardware …
=> Issue #SB-29813 feat:Enabling partial and fuzzy search

core/es-utils/src/main/resources/mappings/org-mapping.json, service/src/main/java/org/sunbird/actor/bulkupload/UserBulkUploadBackgroundJobActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29822" title="SB-29822" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29822</a>  UserOrg Contributor Support
</td></table>
<br />
=> Issue #SB-29822 feat:fixing role issue in upload

core/es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java, core/es-utils/src/main/java/org/sunbird/common/ElasticSearchRestHighImpl.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29813" title="SB-29813" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29813</a>  OrgSearch to allow partial search and fuzzy Search
</td></table>
<br />
* Hardware …
=> Issue #SB-29813 feat:fixed fuzzy issue

service/src/main/java/org/sunbird/actor/bulkupload/OrgBulkUploadBackgroundJobActor.java, service/src/main/java/org/sunbird/actor/notes/NotesManagementActor.java, service/src/main/java/org/sunbird/actor/organisation/OrganisationManagementActor.java
=> Release 4.10.0

pom.xml
=> SB-30251 build failure due to test-cases

core/es-utils/src/main/java/org/sunbird/common/ElasticSearchHelper.java, core/es-utils/src/main/java/org/sunbird/common/ElasticSearchRestHighImpl.java, core/es-utils/src/main/java/org/sunbird/dto/SearchDTO.java, core/es-utils/src/main/resources/mappings/org-mapping.json, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/resources/externalresource.properties, service/src/main/java/org/sunbird/actor/bulkupload/OrgBulkUploadBackgroundJobActor.java, service/src/main/java/org/sunbird/actor/bulkupload/UserBulkUploadBackgroundJobActor.java, service/src/main/java/org/sunbird/actor/notes/NotesManagementActor.java, service/src/main/java/org/sunbird/actor/organisation/OrganisationManagementActor.java, service/src/main/java/org/sunbird/actor/user/IdentifierFreeUpActor.java, service/src/main/java/org/sunbird/actor/user/UserUpdateActor.java, service/src/main/java/org/sunbird/service/user/ResetPasswordService.java, service/src/main/java/org/sunbird/service/user/impl/UserOrgServiceImpl.java, service/src/test/java/org/sunbird/actor/user/IdentifierFreeUpActorTest.java, service/src/test/java/org/sunbird/actor/user/UserUpdateActorTest.java
=> Issue #SB-30586 feat:merge release4.10 to master

core/platform-common/src/main/java/org/sunbird/exception/ResponseMessage.java, service/src/main/java/org/sunbird/actor/bulkupload/UserBulkUploadBackgroundJobActor.java, service/src/main/java/org/sunbird/service/user/impl/SSOUserServiceImpl.java
=> Issue #SB-30586 feat:Bulk user upload issue with new org

pom.xml
=> Issue #SB-30586 feat:added fork count

service/src/main/java/org/sunbird/actor/bulkupload/UserBulkUploadBackgroundJobActor.java
=> Issue #SB-30585 feat:fixed bulk upload issue

service/src/main/java/org/sunbird/actor/bulkupload/UserBulkUploadBackgroundJobActor.java
=> Sb 30585 v3

service/src/main/java/org/sunbird/actor/organisation/OrganisationBackgroundActor.java
=> Issue #SB-30682 feat:fixed org location issue

service/src/main/java/org/sunbird/actor/organisation/OrganisationBackgroundActor.java
=> Issue #SB-30682 feat: fixed org location issue

core/platform-common/src/main/java/org/sunbird/cloud/CloudService.java, core/platform-common/src/main/java/org/sunbird/cloud/CloudServiceFactory.java, core/platform-common/src/main/java/org/sunbird/cloud/aws/AwsCloudService.java, core/platform-common/src/main/java/org/sunbird/cloud/aws/AwsConnectionManager.java, core/platform-common/src/main/java/org/sunbird/cloud/aws/AwsFileUtility.java, core/platform-common/src/main/java/org/sunbird/cloud/azure/AzureCloudService.java, core/platform-common/src/main/java/org/sunbird/cloud/azure/AzureConnectionManager.java, core/platform-common/src/main/java/org/sunbird/cloud/azure/AzureFileUtility.java, core/platform-common/src/main/java/org/sunbird/cloud/gcp/GcpCloudService.java, core/platform-common/src/main/java/org/sunbird/cloud/gcp/GcpConnectionManager.java, core/platform-common/src/main/java/org/sunbird/cloud/gcp/GcpFileUtility.java, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/resources/externalresource.properties, core/platform-common/src/test/java/org/sunbird/azure/AzureServiceFactoryTest.java, core/platform-common/src/test/java/org/sunbird/cloud/aws/AwsServiceTest.java, core/platform-common/src/test/java/org/sunbird/cloud/gcp/GcpServiceTest.java, service/src/main/java/org/sunbird/actor/fileuploadservice/FileUploadServiceActor.java
=> Issue #LR-103 feat:CSP related change for user-org

core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/resources/externalresource.properties, service/src/main/java/org/sunbird/actor/fileuploadservice/FileUploadServiceActor.java
=> Lr 110- CSP change

core/platform-common/src/main/resources/externalresource.properties
=> Issue #SB-30930 feat:updated pdata version

core/platform-common/src/main/java/org/sunbird/cloud/aws/AwsConnectionManager.java, core/platform-common/src/main/java/org/sunbird/cloud/aws/AwsFileUtility.java, core/platform-common/src/main/java/org/sunbird/cloud/azure/AzureFileUtility.java, core/platform-common/src/main/java/org/sunbird/cloud/gcp/GcpConnectionManager.java, core/platform-common/src/main/java/org/sunbird/cloud/gcp/GcpFileUtility.java
=> Issue #LR-110 feat: fixed CSP connection issue

core/platform-common/pom.xml
=> Issue #LR-110 feat: upgraded cloud sdk

core/platform-common/pom.xml
=> Issue #LR-110 feat: updated cloud sdk version

service/src/main/java/org/sunbird/actor/notes/NotesManagementActor.java
=> ED-610 - Note Read API - Bug Fixing 500 Internal Error

core/platform-common/src/main/resources/externalresource.properties
=> LR-242T changes in telemetry version

controller/conf/application.conf
=> LR-311 - making authentication enabled true

controller/app/controllers/feed/validator/FeedRequestValidator.java, core/platform-common/src/main/java/org/sunbird/validator/BaseRequestValidator.java, core/platform-common/src/main/resources/application.conf, core/platform-common/src/test/java/org/sunbird/validator/BaseRequestValidatorTest.java, service/src/main/java/org/sunbird/actor/notes/NotesManagementActor.java, service/src/main/java/org/sunbird/service/user/UserProfileReadService.java, service/src/main/java/org/sunbird/service/user/impl/UserServiceImpl.java, service/src/main/resources/application.conf, service/src/test/java/org/sunbird/service/user/UserServiceImplTest.java
=> LR-310 - Adding logic for covering extra scenarios for making authentication optional

core/platform-common/src/main/resources/externalresource.properties
=> updating the telemetry version

controller/app/controllers/feed/validator/FeedRequestValidator.java, controller/conf/application.conf, core/platform-common/src/main/java/org/sunbird/validator/BaseRequestValidator.java, core/platform-common/src/main/resources/application.conf, core/platform-common/src/main/resources/externalresource.properties, core/platform-common/src/test/java/org/sunbird/validator/BaseRequestValidatorTest.java, service/src/main/java/org/sunbird/actor/notes/NotesManagementActor.java, service/src/main/java/org/sunbird/service/user/UserProfileReadService.java, service/src/main/java/org/sunbird/service/user/impl/UserServiceImpl.java, service/src/main/resources/application.conf, service/src/test/java/org/sunbird/service/user/UserServiceImplTest.java
=> Merge Release-5.1.0 to master

core/platform-common/src/main/resources/externalresource.properties
=> updated telemetry version

service/src/main/java/org/sunbird/actor/organisation/OrganisationManagementActor.java
=> LR-625 key not uploading when same old name is used

.gitignore, core/platform-common/pom.xml, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/java/org/sunbird/util/CloudStorageUtil.java
=> Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.1.0

.gitignore, core/platform-common/pom.xml, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/java/org/sunbird/util/CloudStorageUtil.java
=> Issue #LR-627 merge: OCI CSP changes from release-5.0.2 to release-5.2.0

core/platform-common/src/main/java/org/sunbird/sso/impl/KeyCloakServiceImpl.java, service/src/test/java/org/sunbird/service/user/UserProfileReadServiceTest.java
=> Issue #LR-203 debug: Keycloak Service debug

core/platform-common/pom.xml, core/platform-common/src/main/java/org/sunbird/sso/impl/KeyCloakServiceImpl.java
=> LR-647 bug keycloak connection issue

core/platform-common/pom.xml
=> LR-647-release-5.3.1 bug: keycloack rest-api issue

.gitignore, Jenkinsfile, controller/pom.xml, controller/test/controllers/organisationmanagement/OrganisationControllerTest.java, core/es-utils/pom.xml, core/notification-utils/dependency-reduced-pom.xml, core/notification-utils/pom.xml, core/platform-common/pom.xml, core/platform-common/src/test/java/org/sunbird/util/ProjectUtilTest.java, pom.xml, service/src/test/java/org/sunbird/actor/organisation/OrgManagementActorTest.java
=> Issue #LR-627 merge: From release-5.3.1 to 5.4.0

controller/app/controllers/otp/validator/OtpRequestValidator.java, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, service/src/main/java/org/sunbird/util/otp/OTPUtil.java
=> Issue #LR-676 feat: Delete user Notification

core/platform-common/src/main/java/org/sunbird/kafka/InstructionEventGenerator.java, core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java, core/platform-common/src/main/java/org/sunbird/telemetry/dto/TelemetryBJREvent.java, service/src/main/java/org/sunbird/actor/user/UserDeletionBackgroundJobActor.java, service/src/main/java/org/sunbird/actor/user/UserOwnershipTransferActor.java, service/src/test/java/org/sunbird/actor/user/UserDeletionBackgroundJobActorTest.java
=> Issue #LR-7:feat Added traceability data for event in del-user and own-trans

api-tests/Collections/UserOrg_APIs Test.postman_collection.json, api-tests/Collections/UserOrg_APIs.postman_collection.json, api-tests/Collections/UserOrg_Environment.postman_environment.json
=> postman pre-requisite script addition
