- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/Util.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/test/java/org/sunbird/common/models/util/ProjectUtilTest.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/UserManagementActorTest.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserUtilTest.java
Allow only 30 managed users to be created under LIUA:
- Create a toggle to throttle managed users limit. By default, this is ON. [limit_managed_user_creation=true]
- Introduce a configuration variable - managed_user_limit. By default, this is 30. [managed_user_limit=30]
> SH-175 Allow only 30 managed users to be created under LIUA

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/OTPUtil.java
SH-373 When a user is trying to register with a year (<18 years of age) then, OTP message is not displayed as expected. Code was missing due to merge issue.
> SH-373 OTP message fix

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/OrganisationManagementActor.java
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/tac/UserTnCActor.java
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/Util.java
- actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/OrgManagementActorTest.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserExternalIdManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/dao/impl/UserExternalIdentityDaoImpl.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/SupportMultipleExternalIdsTest.java
usr_external_identifier table primary key changed from (externalId, provider, idtype) to (userId, provider, idtype).
The reads happening from the table was mostly with userId only. It was using 'allow filtering' and searching based on secondary indexing. This puts a load on all cassandra nodes in the cluster.
Given that the primary key has now changed we can query by properties itself. This will put load only on the particular node, where the record exists.
> SB 19442 ExternalId table related code changes

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkMigrationActor.java
portal faced issue while uploading shadowuser details.
problem : Request object contains "starttime" key which is of long type and previously for processing telemetry we had a empty check for strings in the Request map.
Empty check is not necessary.
> Issue #SB-19549 Fix start time type for telemetry

- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/location/LocationClient.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/actor-util/src/main/java/org/sunbird/actorutil/location/impl/LocationClientImpl.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserExternalIdManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
Previously we are saving location codes to usr_external_identity table, now in order make symmetric across application we are saving location ids.
Changes done to update and read api accordingly, so that portal won't get affected.
Because of this user self-declared report also affected.
removing status column updation on every declared-field value
> SH-691 save location id instead of location codes

- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/userencryption.properties
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java
In Read api for old data, if the location is not found with location-id search call application is throwing "USER_DATA_ENCRYPTION_ERROR" since the whole logic is encapsulated with Data-encryption try-catch.
Old data will have location code saved in the usr_external_identity, so location details can't be searched with location-code.
> SB-19871 USER_DATA_ENCRYPTION_ERROR in read api

- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
- service/app/controllers/usermanagement/UserController.java
v1/user/read can throw an error that the user is not found. This is primarily because v1/user/create is used mostly in single sign-on and it tries to update ElasticSearch in an async way. The pattern of this call is also incorrect that it tells the ES actor after sending a response. In a high load system, this could be fatal.
> SB-19892: SSO onboarding throws v1/user/read failure 

- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
Update api is failing during valid userId operation due to null pointer exception
getUserId is a common function, hence it should get the userId from request message during validation if not found then only check userExternalId service to get it through ext,provider,idtype
> SB-20052 update api fix

- .circleci/config.yml
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/tenantpreference/TenantPreferenceManagementActor.java
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/util/Util.java
- actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/tenantpreference/TenantPreferenceManagementActorTest.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseCode.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/responsecode/ResponseMessage.java
- service/app/controllers/tenantpreference/TenantPreferenceController.java
- service/app/controllers/tenantpreference/TenantPreferenceValidator.java
- service/app/util/RequestInterceptor.java
- service/test/controllers/tenantpreference/TenantPreferenceControllerTest.java
Api endpoint: **v1/org/preferences/create**
Request :  `{
"request": {
"orgId": "", //mandatory
"key": "",//mandatory
"data": {}//mandatory
}
}`
Response:  
-  **success response**`{
"id": "api.org.preferences.create",
"ver": "v1",
"ts": "2020-08-04 18:40:47:142+0530",
"params": {
"resmsgid": null,
"msgid": "52b2e453-09bb-4cf3-b5a5-fa3dda1335b5",
"err": null,
"status": "success",
"errmsg": null
},
"responseCode": "OK",
"result": {
"response": "SUCCESS",
"orgId": "2323",
"key": "teacher"
}
}`
- **Missing param** `{
"id": "api.org.preferences.create",
"ver": "v1",
"ts": "2020-08-04 18:40:06:376+0530",
"params": {
"resmsgid": null,
"msgid": "d09558a0-2a4b-4023-8421-5a305b79ca06",
"err": "MANDATORY_PARAMETER_MISSING",
"status": "MANDATORY_PARAMETER_MISSING",
"errmsg": "Mandatory parameter …
> SC-1883: Enhance create tenant preference api

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkMigrationActor.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/datasecurity/impl/DefaultDecryptionServiceImpl.java
- service/app/controllers/bulkapimanagement/BaseBulkUploadController.java
- service/app/util/RequestInterceptor.java
1. We have some observations that there are decrypt errors getting logged frequently. This could be happening on expected lines or not, due to legacy. This logging of value to be decrypted can help find this out - this will be reverted based on our experiment results.
2. In token verification, some null pointer exception is thrown. Adding a trace and softly ignoring this, as we could afford to for managed for tokens.
> SB-19287 Add explicit logs

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/OrganisationManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/TenantMigrationActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserManagementActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserProfileReadActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserExternalIdentityService.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/impl/UserExternalIdentityServiceImpl.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/SupportMultipleExternalIdsTest.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/service/UserExternalIdentityServiceTest.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserUtilTest.java
Update:
Fix to read SSO user to work with usr_external_identity table with orgId
Migrate user to update orgId in the usr_external_identity table.
Refactor code to reuse the components
> SB-20253 Fix migrate user and SSo user read api to work with usr_external_identity migration

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/DeclaredExternalIdActor.java
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkMigrationActor.java
- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/validator/user/UserBulkMigrationRequestValidator.java
- actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/validator/user/UserBulkMigrationRequestValidatorTest.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/src/main/resources/externalresource.properties
Removed orgid column and its related mandatory validation from self-user bulkupload csv.
Removed validation that is checking for duplicate user external id(State provided ext. ID).
> SH-999 Remove org id column and use channel as main identifier

- actors/sunbird-lms-mw/actors/sunbird-utils/sunbird-platform-core/common-util/pom.xml
user is unable to block the account through block API: changed keycloak-admin-client version from 6.2.0 to 3.2.0.Final
> SB-17965: changed keycloak-admin-client version  to 3.2.0.Final

- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/dao/UserExternalIdentityDao.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/dao/impl/UserExternalIdentityDaoImpl.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/impl/UserExternalIdentityServiceImpl.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/service/UserExternalIdentityServiceTest.java
getUserIdByExternalId() was using  usr_external_identity table, to get userId, now it is redirected to user_lookup table
@sknirmalkar89  mentioned that getCaseInsensitiveOrgFromProvider() is not merged in release-3.3.0, getCaseInsensitiveOrgFromProvide() added back
> SC-2021: Redirect the call to user_lookup table - getUserIdByExternalId() in UserExternalIdentityDaoImpl

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkUploadBackgroundJobActor.java
Had checked the APIs /v1/user/create,/v2/user/create, /v3/user/create, /v4/user/create,/v1/user/signup By default Public role is been added in all these cases. roles are added in both user and user-organization table. Even if roles are sent explicitly in the req it is not picked.
/v1/user/upload and /v1/user/upload, by default  public role, is not added  in both user and user-organization table and if roles are sent explicitly in the CSV it is picked(note: roles are mandatory in CSV file), If roles in the CSV  doesn't contain public role, added public role by default(this PR has the changes),
> SC-1954: Ensure public role always with a valid user

- Jenkinsfile
- auto_build_deploy
Without auto-deploy, non-dev environments progression wont happen.
`mvn test` still fails and this is a stop gap arrangement until we find the right way to address this.
> SC-2026 Fix autodeploy script

- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/actors/UserMergeActor.java
- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/util/UserUtil.java
- actors/sunbird-lms-mw/actors/user/src/test/java/org/sunbird/user/util/UserUtilTest.java
During user-merge scenario, we are nullyfing username, phone and email of mergee details.
When any new account is creating with same mergee details again(say email, phone), application is saying email already exists.
So mergee details are removed from user_lookup table.
> Sb 20852 Deleting email,phone and username from user_lookup in account merge scenario

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/bulkupload/UserBulkMigrationActor.java
Instead of comparing mappedCsvHeader(which contain filtered columns like supported and mandatory fields) we will compare each row size with csvHeaders list(which contains actual columns of the uploaded csv) size.
Comparing each row is mandatory since, users may unknowing repeats the contents of a row, in that case row size may increase when compare to actual csv header size and one column value can be shifted to another column.
> SH-999 comparing header size with each entry of csv

- actors/sunbird-lms-mw/actors/common/src/main/java/org/sunbird/learner/actors/tac/UserTnCActor.java
- actors/sunbird-lms-mw/actors/common/src/test/java/org/sunbird/learner/actors/UserTnCActorTest.java
- service/app/util/RequestInterceptor.java
- service/conf/routes
In user TnC request we are not expecting userid for custodian-user in the request, only for MUA users we expect userid.
Recently we tighten this on these grounds.
But APP is broken since we are getting userid for custodians also from beginning, so this is conveyed to APP.
Further modified the condition.
> SB-21219 checking MUA user is present or not in the tnc request

- actors/sunbird-lms-mw/actors/user/src/main/java/org/sunbird/user/service/UserProfileReadService.java
Read api's change:
for older versions v1/v1/v3/v4, user roles is showing data from roles column from user table, it shouldn't show.
for new verison v5, roles data is picking from user_organisation table, if organisation contains any.
> SB-25314 user-read api changes for roles

- service/src/main/java/org/sunbird/actor/user/UserSelfDeclarationManagementActor.java
- service/src/main/java/org/sunbird/util/user/UserUtil.java
- service/src/test/java/org/sunbird/actor/user/UserSelfDeclarationManagementActorTest.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-27874" title="SB-27874" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-27874</a>  Update audit fields along with declaration data
</td></table>
<br />
> Issue #SB-27874 feat:updating audit data with user declaration

- service/src/main/java/org/sunbird/actor/user/TenantMigrationActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28404" title="SB-28404" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-28404</a>  [SSO > Global consent] If user has given consent in profile for Tamil Nadu tenant and migrated to TN (Same tenant) tenant through SSO then, global consent popup is not coming after login
</td></table>
<br />
Use root org instead of org id as consent can be revoked using school id which is not a tenant
> SB-28404:[SSO > Global consent]issue:update consumer_id,object_id with root org id

- service/src/main/java/org/sunbird/actor/user/TenantMigrationActor.java
- service/src/main/java/org/sunbird/actor/userconsent/UserConsentActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28404" title="SB-28404" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-28404</a>  [SSO > Global consent] If user has given consent in profile for Tamil Nadu tenant and migrated to TN (Same tenant) tenant through SSO then, global consent popup is not coming after login
</td></table>
<br />
UI pop up only when consent not found exception occurs ,hence throwing exception when list is empty after removing REVOKED consent.
> SB-28404:SB-28404:[SSO > Global consent]issue:Throw consent not found exception list is empty

- service/src/main/java/org/sunbird/actor/bulkupload/OrgBulkUploadBackgroundJobActor.java
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-30251" title="SB-30251" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />SB-30251</a>  Bulk org upload API(/api/org/v1/upload) issue
</td></table>
<br />
> Issue #SB-30251 fix: Bulk org upload API(/api/org/v1/upload) issue

- core/platform-common/src/main/java/org/sunbird/sso/impl/KeyCloakServiceImpl.java
- service/src/test/java/org/sunbird/service/user/UserProfileReadServiceTest.java
- service/src/test/java/org/sunbird/util/user/UserUtilTest.java
> Issue #LR-203 debug: Keycloak Service debug

- controller/app/controllers/otp/validator/OtpRequestValidator.java
- core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java
> Issue #LR-676 feat: User Delete

- core/platform-common/src/main/java/org/sunbird/kafka/InstructionEventGenerator.java
- core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java
- service/src/main/java/org/sunbird/actor/user/UserDeletionBackgroundJobActor.java
> Issue #LR-676 feat: Delete User API

- .circleci/config.yml
- core/platform-common/src/main/java/org/sunbird/keys/JsonKey.java
- helm/learner/templates/configmap.yaml
- helm/learner/values.yaml
- service/src/main/java/org/sunbird/util/otp/OTPUtil.java
> Issue #LR-676 fix: Support email

- core/es-utils/src/main/java/org/sunbird/common/ElasticSearchRestHighImpl.java
> Issue #LR-766 feat: Fixed Promise error.
